---
title: "Assessment2"
author: "C Rusling"
date: "2024-11-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## Aim

## Load Packages

```{r load packages}
library(tidyverse)
library(viridis)   
library(plotly) 
library(here)
library(ggplot2)
library(ggbump)
library(hrbrthemes)
```


## Read in Data

```{r read in data}
dev_data <- read_csv(here("./inputs/dev_concerns_all.csv"))
simd_data <- read_csv(here("./inputs/SIMD 2020v2.csv"))
dev_data_HB <- read_csv(here("./inputs/dev_data_HB_allyrs.csv"))
int_zone_code <- read_csv(here("./inputs/iz2011_codes_and_labels_21042020.csv"))
```


## Prepare Data
```{r glimpse data for Developmental Concerns at 27-30 months}
dev_data %>% glimpse

```




## Filter data to keep only the variables needed

```{r filter variables}

iz_dev_data <- dev_data %>%  
  filter(area_type == "Intermediate zone") %>%
  select(area_name, area_code, year, measure) 
glimpse(iz_dev_data)

iz_info <- int_zone_code %>%
  select(IntZone,HBName)

iz_simd <- simd_data %>% 
  select(IntZone, HB, SIMD2020V2HBQuintile)
glimpse(simd_HB)
```
## Calculate mean SIMD for intermediate zones


```{r mean SIMD intermediate zones}
iz_simd_mean <- iz_simd %>%
  group_by(IntZone) %>%
  mutate(mean_simd=mean(SIMD2020V2HBQuintile, na.rm = T)) %>%
  data.frame() 
```

```{r distinct SIMD}
iz_simd_mean <- iz_simd_mean %>%
  distinct(IntZone, .keep_all = T) %>%
  select(IntZone, HB, mean_simd)
```

## Join datasets
```{r join developmental data and mean SIMD data}
dev_simd <- full_join(iz_dev_data, iz_simd_mean, by = c("area_code" = "IntZone"))
```
```{r join new dataset with area labels}
dev_simd <- left_join(dev_simd, iz_info, by = c("area_code" = "IntZone"))
```

## Rename variables
```{r rename variables}
dev_simd <- dev_simd %>%
  mutate(HBName = gsub("NHS", "", HBName)) %>%
  rename(health_board = HBName, intermediate_zone = area_name, iz_code = area_code, HB_code = HB, percent_concern = measure) 
```
```{r reorder variables}
dev_simd <- dev_simd %>%
 select(health_board, HB_code, intermediate_zone, iz_code, year, percent_concern, mean_simd) %>%
  rename(mean_iz_simd = mean_simd)
```


## Plot Graph 

```{r}
ggplot(dev_data_HB, aes(x=year, y=measure)) + 
    geom_point() +
  facet_wrap(~area_name)
```
```{r}
ggplot(dev_data_HB, aes(x = year, y = measure, colour = area_name)) +
  geom_bump()
```


